### ISSUE TITLE
Unable to build tamagui example on macos

### ISSUE THREAD

**Issue by siddarthkay** [natew/vxrn#11]
Hello!
I wanted to try building vite for react-native and here is what I tried after cloning this repo.
- `cd vxrn`
- `yarn install`
- `yarn dev:example-tamagui`

Here is what I see : 
```
yarn dev:example-tamagui
node:internal/modules/cjs/loader:446
      throw err;
      ^

Error: Cannot find module '/Users/siddarthkumar/code/siddarthkay/vxrn/node_modules/vxrn/dist'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:687:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1068:27)
    at Module._resolveFilename (/Users/siddarthkumar/code/siddarthkay/vxrn/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/siddarthkumar/code/siddarthkay/vxrn/examples/tamagui/dev.ts:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._compile (/Users/siddarthkumar/code/siddarthkay/vxrn/node_modules/esbuild-register/dist/node.js:2258:26) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/siddarthkumar/code/siddarthkay/vxrn/node_modules/vxrn/package.json',
  requestPath: 'vxrn'
}

Node.js v20.1.0
```

I am really excited to try this out, could you please provide some assistance or guidance on how to deal with this?

Is this an issue with my environment? 

Thanks for the hard work!

**Comment by natew** [comment]
Oh yea do a build first, sorry forgot to add that: `yarn build`

**Comment by siddarthkay** [comment]
> forgot to add that

I'd be happy to send in a PR for that

It works after `yarn build` thanks!
